const sampleData = {
  products: [
    {
      name: 'پیراهن کشی ورزشی پولو',
      slug: 'polo-sporting-stretch-shirt',
      category: 'پیراهن مردانه',
      description: 'استایل کلاسیک پولو همراه با راحتی مدرن',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'پولو (Polo)',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'پیراهن آستین بلند بروکز برادرز',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: 'پیراهن مردانه',
      description: 'استایل ماندگار و کیفیت متمایز و راحت',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.9,
      brand: 'بروکز برادرز (Brooks Brothers)',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'پیراهن رسمی کلاسیک تامی هیلفیگر',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: 'پیراهن مردانه',
      description: 'ترکیبی بی‌نظیر از آراستگی و راحتی در طول روز',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'تامی هیلفیگر (Tommy Hilfiger)',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'پیراهن اندامی کشی کلوین کلاین',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: 'پیراهن مردانه',
      description: 'طراحی متمایز و خوش‌دوخت با پارچه کشی و انعطاف‌پذیر',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'کلوین کلاین (Calvin Klein)',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'پیراهن آکسفورد پولو رالف لورن',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: 'پیراهن مردانه',
      description: 'طراحی اصیل پولو با پارچه آکسفورد باکیفیت و ریزبافت',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'پولو (Polo)',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'هودی صورتی کلاسیک پولو',
      slug: 'polo-classic-pink-hoodie',
      category: 'سویشرت و هودی مردانه',
      description: 'نرم، شیک و کاملاً ایده‌آل برای روزهای روزمره و پاییزی',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'پولو (Polo)',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;